[package]
name = "verify"
version.workspace = true
edition.workspace = true

[lib]
name = "verify"
crate-type = ["rlib"]

[dependencies.pyo3]
workspace = true

[dependencies.thiserror]
workspace = true

[dependencies.rand]
workspace = true